$(function()
{
$('#alertMe').click(function(e)
{
e.preventDefault();
$('#successAlert').slideDown();
});
$('#alertSuccess').click(function(e)
{
e.preventDefault();
$('#registerAlert').slideDown();
});
});